### ISSUE TITLE
Fails with the latest version of Docker

### ISSUE THREAD

**Issue by sunyal** [P3GLEG/WhaleTail#1]
Unable to use the tool with the Docker version `Version 18.03.1-ce-mac65 (24312)`

```
> ./WhaleTail pegleg
Error response from daemon: client version 1.38 is too new. Maximum supported API version is 1.37
```

Seems like this is a limitation right now with the docker client API

https://github.com/moby/moby/blob/53683bd8326b988977650337ee43b281d2830076/api/server/middleware/version.go#L39

How would I go about using the 1.12.x branch for the go build?

**Comment by P3GLEG** [comment]
I was able to reproduce this. It's due to some recent changes to the docker client API. I had an older dependency. I will update it ASAP. For now, you can do this as a quick fix while I look into it further.

`
cd $GOPATH/src/github.com/docker/docker
git checkout 8e2f9203065987116aec9e2d2a1d5c7039e1a5d4
cd $GOPATH/src/WhaleTail
go build .
./WhaleTail nginx:latest
`

**Comment by P3GLEG** [comment]
I was able to fix this for you. There is a new flag -sV which will allow you to specify the version of your Docker Server daemon like so

`./WhaleTail -sV=1.12 nginx:latest`

Thanks for bringing it to my attention.

**Comment by sunyal** [comment]
Great thanks
